### ISSUE TITLE
marble corinthian capital vertical quarter no "west" property

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#246]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.9p

**Forge Version**    
Forge 31.2.45

**Describe the bug**    
world editing copy and paste either straight or with flip or rotate all pop up with the same console error - 
"no property named west"  it then breaks the paste
![corinthian capital west](https://user-images.githubusercontent.com/66781812/103418978-f1d78180-4b88-11eb-93dd-1d817c82e7bd.jpg)

**Crash Log**    
N/A

**Screenshots/Video**    
as above

**System Information (optional)**    
N/A

**Additional context**    
Have not checked to see if this issue persists with other versions of the vertical quarters

**Comment by HIPPOKLEIDES** [comment]
Managed to fix this for the next alpha mod release. It seems that if worldedit detects a blockstate property named after one of the cardinal directions, it needs all four, otherwise it throws this error. Renaming the property works, but will unfortunately reset the renamed blockstates in existing worlds
