### ISSUE TITLE
cyan and green terracotta blocks growing down like vines

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#325]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.13

**Forge Version**    
31.2.49

**Describe the bug**    
Solid blocks for green_terracotta and cyan_terracotta are growing downwards like vines, removing the blocks below.  I've been running my server for about 15 hours now since pasting in some schematics, and in comparison to the world backup from last week and previous, my houses are currently being consumed by their roofs.  

**Crash Log**    
None so far, server is running without an issue however on each login I get the following 2 error codes - no idea if this is relevant or even anything to do with this bug.
14.04 07:22:23 [Server] Netty Epoll Server IO #2/ERROR Could not serialize net.minecraftforge.server.command.ModIdArgument@1307c380 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
14.04 07:22:23 [Server] Netty Epoll Server IO #2/ERROR Could not serialize net.minecraftforge.server.command.EnumArgument@4632f089 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!

**Screenshots/Video**    
Backup from last week shows houses were all fine - 
![2021-04-15_01 18 54](https://user-images.githubusercontent.com/66781812/114797882-0d5b4680-9d8c-11eb-8fa5-d32be920cfb7.png)
Current state of build - 
![2021-04-15_01 14 30](https://user-images.githubusercontent.com/66781812/114797906-18ae7200-9d8c-11eb-9476-151076e24426.png)
![2021-04-15_01 36 26](https://user-images.githubusercontent.com/66781812/114797939-295ee800-9d8c-11eb-9c2d-76a751a3efbc.png)
![2021-04-15_01 36 50](https://user-images.githubusercontent.com/66781812/114797945-2b28ab80-9d8c-11eb-87ae-8737123fdac4.png)
![2021-04-15_01 37 34](https://user-images.githubusercontent.com/66781812/114797947-2cf26f00-9d8c-11eb-99e5-de63f2e7ec66.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
An explanation I found for the Netty errors: 

"The errors about serialization of arguments can also be ignored. One of Forge's goals is interoperability with vanilla: Forge clients can connect to vanilla servers, and vanilla clients can connect to Forge servers. The errors occur because Forge doesn't serialize the arguments to be sent to clients; if the clients were vanilla, then sending those command arguments to the client can confuse it and may cause issues and crashes. (If you're thinking, "Why not only check if it's a Forge client?", because that would require changing the Brigadier library, which would be another can of worms.)"

So it makes sense this would show up when logging in, and it's unlikely that it's connected to the issue. 

Feel free to share the latest.log of your server while this is happening. Might be able to assist. In any case, it seems unlikely that this issue is originating from the mod as I haven't seen this occurring for other servers or servers I've been on

**Comment by xElandriax** [comment]
Seems to have stopped, so whatever it was it was very intermittent, Thanks for looking into the netty errors! I'll close this down cause I can't replicate the issue anyhow.
