### ISSUE TITLE
z-fighting on side of wooden towel rail #322 - not fixed and on clothes rail

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#326]
v13.1 

As mentioned in the reply to the previously closed bug #322  - this is not fixed.  Z-fighting is now happening on both the back and the sides. 

The clothes rails are also having the same z-fighting issues.

![2021-04-17_16 08 58](https://user-images.githubusercontent.com/66781812/115117758-0a34a600-9f98-11eb-8e1d-fc330d0668b3.png)
![2021-04-17_16 09 11](https://user-images.githubusercontent.com/66781812/115117761-0bfe6980-9f98-11eb-9281-51448f021ea9.png)
![2021-04-17_16 16 00](https://user-images.githubusercontent.com/66781812/115117796-3e0fcb80-9f98-11eb-8a0b-bba5d7cb77b2.png)
![2021-04-17_16 16 08](https://user-images.githubusercontent.com/66781812/115117799-40722580-9f98-11eb-9986-7ad53ec6449e.png)

Suggestion - make all the edges thicker to look like they are actual structural supports. Same as the rear portion of the clothes rail which sits proud of the block behind it.

**Comment by HIPPOKLEIDES** [comment]
Have tested the towel rack in both the dev environment and with the latest alpha, haven't been able to recreate this. Other devs can't recreate it either. If you are indeed on v13.1, then it might be some graphics setting causing this (though I've tested a few without seeing any difference. 

The clothes hanger, however, should be fixed in the next alpha update
